module.exports = {
    "account_number": null,
    "bill_to": {
        "address": null,
        "name": null,
        "parsed_address": null,
        "vat_number": null
    },
    "cashback": null,
    "category": "Meals & Entertainment",
    "created_date": "2022-12-25 00:43:29",
    "currency_code": "USD",
    "date": "2022-02-21 19:45:01",
    "delivery_date": null,
    "discount": null,
    "document_reference_number": null,
    "document_title": null,
    "document_type": "receipt",
    "due_date": null,
    "duplicate_of": 110279567,
    "external_id": null,
    "id": 110330611,
    "img_file_name": "110330611.jpg",
    "img_thumbnail_url": "https://scdn.veryfi.com/receipts/7fb6f31d-bcdc-46d9-9eef-65b49ac68d2e/thumbnail.jpg?Expires=1674086197&Signature=YLsCWGtBGukKmTVJ4tT1hAOR0RlEAblqzzPI7Hfn8t3z0eF~z74i4oYqrBQriK7kdXPauVUdOu9u65iDUG1wBCkZ1F2KVSCeHyYHrEivcHyIZuQUKeA-nWQDjX~58EihlGBfmd01SrTWFyFPgHeu1lhjisQlu8~5V67znrd~udnJ23FWQ-4YY5XwPta~QsDvzmxVoKMfXQoj8OM~65Q4TfGHlKZAukStK6A2gOmBUwdpztoBY8BOpusJkLujHTlfUm8znZRdUFDGcgzGbU2qirHWwnhyR4HsAK3WYYGUxq38iUtcx2rL1VbkiAH0G5vIGr9v3LewO~0AKNJVuwIRLA__&Key-Pair-Id=APKAJCILBXEJFZF4DCHQ",
    "img_url": "https://scdn.veryfi.com/receipts/7fb6f31d-bcdc-46d9-9eef-65b49ac68d2e/507190c4-1b08-40a8-b152-90a5e8e3d25d.jpg?Expires=1674086197&Signature=CPkkQnmwmDOE-qjpLz4ijl0U7uzdCNlOPc8t~W3raEckeVweMRnMQ57PhwU2LHHxN-HSFdCU~yXLUCjoIWlaqrTKZJFOjLQkHUKL28vAb-UY-FwMJaZjEk2vHwUI4sWWMAd3NlMSmbJECTxMF5-Q~1l1l7u4GSye~VdOgdTKWAT6mC83bn13hNCpQweCvNg5DulJTtAiuzSL55Azem7QwMSw0O89YBE8Xw7AlHKkfBK~QgjSK-9O0gi-xzeBtNmOn1FOJaRkVcXM9FJCffhO5kXmS3QeKjwCnRDmzNVKWXVp9G9e0VFe5rdefAm6M2kHtjKQ7oJ0AUz4e~zpO0u2WA__&Key-Pair-Id=APKAJCILBXEJFZF4DCHQ",
    "insurance": null,
    "invoice_number": "673271",
    "is_duplicate": true,
    "is_money_in": false,
    "line_items": [
        {
        "date": null,
        "description": "Oreo Shake",
        "discount": null,
        "discount_rate": null,
        "id": 430282025,
        "order": 0,
        "price": null,
        "quantity": 1,
        "reference": null,
        "section": null,
        "sku": null,
        "tax": null,
        "tax_rate": null,
        "text": "Oreo Shake\t\t5.99",
        "total": 5.99,
        "type": "food",
        "unit_of_measure": null,
        "upc": null
        },
        {
        "date": null,
        "description": "Green Smoothie",
        "discount": null,
        "discount_rate": null,
        "id": 430282026,
        "order": 1,
        "price": null,
        "quantity": 1,
        "reference": null,
        "section": null,
        "sku": null,
        "tax": null,
        "tax_rate": null,
        "text": "Green Smoothie\t4.99",
        "total": 4.99,
        "type": "food",
        "unit_of_measure": null,
        "upc": null
        },
        {
        "date": null,
        "description": "Raspberry Tea",
        "discount": null,
        "discount_rate": null,
        "id": 430282027,
        "order": 2,
        "price": null,
        "quantity": 1,
        "reference": null,
        "section": null,
        "sku": null,
        "tax": null,
        "tax_rate": null,
        "text": "Raspberry Tea\t3.59",
        "total": 3.59,
        "type": "food",
        "unit_of_measure": null,
        "upc": null
        },
        {
        "date": null,
        "description": "Coke",
        "discount": null,
        "discount_rate": null,
        "id": 430282028,
        "order": 3,
        "price": null,
        "quantity": 1,
        "reference": null,
        "section": null,
        "sku": null,
        "tax": null,
        "tax_rate": null,
        "text": "Coke\t\t3.59",
        "total": 3.59,
        "type": "food",
        "unit_of_measure": null,
        "upc": null
        },
        {
        "date": null,
        "description": "Coke",
        "discount": null,
        "discount_rate": null,
        "id": 430282029,
        "order": 4,
        "price": null,
        "quantity": 1,
        "reference": null,
        "section": null,
        "sku": null,
        "tax": null,
        "tax_rate": null,
        "text": "Coke\t\t3.59",
        "total": 3.59,
        "type": "food",
        "unit_of_measure": null,
        "upc": null
        },
    ],
    "meta": {
        "owner": "dmilinovichiii"
    },
    "notes": null,
    "ocr_text": "Dine In\nDenny's Restaurant #9527\n1015 BLOSSOM HILL ROAD\nSAN JOSE, CA 95123\n(408) 448-6205\nwww.dennys.com\n2/21/2022\t\t7:45:01 PM\nder:\t673271\tServer: rosalia e\nble: 31 Guests: 11\n1:1\nOreo Shake\t\t5.99\nGreen Smoothie\t4.99\nRaspberry Tea\t3.59\nCoke\t\t3.59\nCoke\t\t3.59\nHot Chocolate\t3.89\nTap Water\t\t0.00\nTap Water\t\t0.00\nTap Water\t\t0.00\nTap Water\t\t0.00\nTap Water\t\t0.00\nTap Water\t\t0.00\nTap Water\t\t0.00\nFlamin 5 Pepper Burger\t13.89\nDbl Chsburger\t15.88\n2 Eggs/CFS\t\t16.39\nCFS Dinner\t\t16.29\nSeason Fries\t1.49\nT-Bone Dnr\t\t19.99\nStack Pancakes\t3.49\nBYO Slam\t\t13.29\nCrazy Spicy Skillet\t14.29\nGarlic Bread\t\t1.59\nSeasoned Fries\t2.99\nSr Salmon Dnr\t10.99\nBourbon Sirloin Dinner\t16.29\nBourbon Sirloin Dinner\t16.29\nGreen Smoothie\t4.99\nS1 Cheesecake\t4.99\nWhipped Top\nKids Ice Cream\t1.29\n1 Sc Straw\nSubTotal\t200.06\nTax\t\t18.71\nTotal\t218.77\n** Please total the check **\nTIP\n\t||\nTOTAL",
    "order_date": null,
    "payment": {
        "card_number": null,
        "display_name": "Visa",
        "terms": null,
        "type": "visa"
    },
    "pdf_url": "https://scdn.veryfi.com/receipts/7fb6f31d-bcdc-46d9-9eef-65b49ac68d2e/780440f2-9681-4a19-a9ed-858b28355629.pdf?Expires=1674086197&Signature=A9lfTgH8yDbCGffRAe9hXZxMJFFRP~jeEUbdRFFOSEViVe4GF9JMF9WYTuOjgpkMKW8rU9FZMdoCQ4E2RpTKuRGZVAxQpL50MEvPlFX6Qc5Sq8QF7ukySD5qxxYCDhlVE0tr6cRZD~MBkkEifB54fzUQHemdtNX8QhZLTsf~5DJLMVt3xx0PP9WIBNodF6pZKApobGYHPwRSBrTBubCEIUbNq7AQ~rJ3lB90uVLR-H2wKjDkPVWNJvFoJgNl09T2fdh2um4OTOMsB4OWZcQ0gvKzc9dEqaEPbAmnYCJ0KI3ddiVaVpPpCiXgZ4X6vfui~CrCSehwI2dSTi1UCvUXGg__&Key-Pair-Id=APKAJCILBXEJFZF4DCHQ",
    "purchase_order_number": null,
    "reference_number": "VJCDD-0611",
    "rounding": null,
    "service_end_date": null,
    "service_start_date": null,
    "ship_date": null,
    "ship_to": {
        "address": null,
        "name": null,
        "parsed_address": null
    },
    "shipping": null,
    "store_number": "9527",
    "subtotal": 200.06,
    "tax": 18.71,
    "tax_lines": [],
    "tip": null,
    "total": 218.77,
    "total_weight": null,
    "tracking_number": null,
    "updated_date": "2022-12-25 00:43:30",
    "vendor": {
        "abn_number": null,
        "account_number": null,
        "address": "1015 Blossom Hill Rd, San Jose, CA 95123",
        "bank_name": null,
        "bank_number": null,
        "bank_swift": null,
        "category": "diners, american (traditional), breakfast & brunch",
        "email": null,
        "fax_number": null,
        "iban": null,
        "lat": 37.2509237499112,
        "lng": null,
        "logo": "https://cdn.veryfi.com/logos/us/951569132.png",
        "name": "Denny's",
        "phone_number": "(408) 448-6205",
        "raw_address": "1015 BLOSSOM HILL ROAD\nSAN JOSE, CA 95123",
        "raw_name": "Denny's",
        "reg_number": null,
        "type": "diners, american (traditional), breakfast & brunch",
        "vat_number": null,
        "web": "www.dennys.com"
    }
}